#!/bin/bash
#
# Copyright (c) 2015, Xerox Corporation (Xerox)and Palo Alto Research Center (PARC)
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright
#       notice, this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Patent rights are not granted under this agreement. Patent rights are
#       available under FRAND terms.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL XEROX or PARC BE LIABLE FOR ANY
# DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
# (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
# LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
# ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
# (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
# SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# @author Nacho "Ignacio" Solis, Palo Alto Research Center (PARC)
# @copyright 2015, Xerox Corporation (Xerox)and Palo Alto Research Center (PARC).  All rights reserved.
#
# SETTING
# location of XCODE docset
DOCSET_DIR=../Docset/com.parc.csl.parc.docset

# location of html code document, generated by headerdoc2html
DOCUMENT_DIR=$DOCSET_DIR/Contents/Resources/Documents

# location of hautelook templates, Info.plist Nodes.xml
DOCSET_TEMPLATE_DIR=./

# location of our source code, where headerdoc2html will spider through
SOURCE_DIR=../algol/

# clear screen
clear

# delete old docset and start from fresh, this will kill XCODE if its running.  good for development only, comment out for production.
rm -rf $DOCSET_DIR

# create document directory
mkdir -p $DOCUMENT_DIR

# generate html code document for source code.  -j will recognize java comment tag ex. /** */
# https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/HeaderDoc/usage/usage.html#//apple_ref/doc/uid/TP40001215-CH337-SW2
headerdoc2html --config-file headerDoc2HTML.config --class-as-composite -j -o $DOCUMENT_DIR $SOURCE_DIR
#headerdoc2html  -j -o $DOCUMENT_DIR $SOURCE_DIR/*.h

# generate main index file. -d will generate Tokens.xml for us.
#
# http://opensource.apple.com/source/headerdoc/
# https://developer.apple.com/library/mac/documentation/DeveloperTools/Conceptual/HeaderDoc/usage/usage.html#//apple_ref/doc/uid/TP40001215-CH337-SW1
#
gatherheaderdoc -d $DOCUMENT_DIR

# copy required template files for apple docset
cp $DOCSET_TEMPLATE_DIR/Info.plist $DOCSET_DIR/Contents/
cp $DOCSET_TEMPLATE_DIR/Nodes.xml   $DOCSET_DIR/Contents/Resources/
cp $DOCUMENT_DIR/Tokens.xml         $DOCSET_DIR/Contents/Resources/

# create and validate apple docset indexes
/Applications/Xcode.app/Contents/Developer/usr/bin/docsetutil index -verbose -debug $DOCSET_DIR
/Applications/Xcode.app/Contents/Developer/usr/bin/docsetutil validate -verbose -debug $DOCSET_DIR

